
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hola-deployment
  name: hola-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: hola-deployment
  template:
    metadata:
      labels:
        app: hola-deployment
    spec:
      containers:
      - image: ucreativaregistryclase10.azurecr.io/holatest:1.0.0
        name: python-service
      nodeSelector:
        processing: "aqui"
---
apiVersion: v1
kind: Service
metadata:
  name: hola-service
spec:
  type: LoadBalancer
  ports: 
    - targetPort: 2000
      port: 2000
  selector: 
     app: hola-deployment