version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=micro123  
    ports:
        - "27017:27017"
    networks:
        - microservices
  sumas:
    build: ../service-suma/.
    container_name: service-suma
    environment: 
        - MONGO_SERVER=mongo
        - MONGO_USER=admin
        - MONGO_PWD=micro123
    ports: 
        - "8080:8080"
    networks:
        - microservices
  multiplicaciones:
    build: ../service-multiplicacion/.
    container_name: service-multiplicacion
    environment: 
        - MONGO_SERVER=mongo
        - MONGO_USER=admin
        - MONGO_PWD=micro123
    ports: 
        - "8081:2000"
    networks:
        - microservices
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=micro123
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
    ports:
        - "8082:8081"
    networks:
        - microservices
    depends_on:
        - mongo
networks:
  microservices:
    name: microservices